<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Project Test</title>
    <meta name="description" content="A preview of the jQuery UI Bootstrap theme">
    <meta name="author" content="Addy Osmani">
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!-- Styles --> 
    <link type="text/css" href=<?=$this->basePath()?>"/css/custom-theme/jquery-ui-1.8.16.custom.css" rel="stylesheet" />
    <link href=<?=$this->basePath()?>"/bootstrap/bootstrap.css" rel="stylesheet">
    <link href=<?=$this->basePath()?>"/css/demo.css" rel="stylesheet">
    <link href=<?=$this->basePath()?>"/third-party/jQuery-UI-Date-Range-Picker/css/ui.daterangepicker.css" media="screen" rel="Stylesheet" type="text/css" />
      <script type="text/javascript" src=<?=$this->basePath()?>"/js/jquery-1.6.2.min.js"></script>
        <script type="text/javascript" src=<?=$this->basePath()?>"/js/jquery-ui-1.8.16.custom.min.js"></script>
        <!--daterangepicker-->
        <script type="text/javascript" src=<?=$this->basePath()?>"/third-party/jQuery-UI-Date-Range-Picker/js/date.js"></script>
        <script type="text/javascript" src=<?=$this->basePath()?>"/third-party/jQuery-UI-Date-Range-Picker/js/daterangepicker.jQuery.js"></script>
        <!--wijmo-->
        <script src=<?=$this->basePath()?>"/third-party/wijmo/jquery.mousewheel.min.js" type="text/javascript"></script>
        <script src=<?=$this->basePath()?>"/third-party/wijmo/jquery.bgiframe-2.1.3-pre.js" type="text/javascript"></script>
        <script src=<?=$this->basePath()?>"/third-party/wijmo/jquery.wijmo-open.1.5.0.min.js" type="text/javascript"></script>
        <!-- FileInput -->
        <script src=<?=$this->basePath()?>"/third-party/jQuery-UI-FileInput/js/enhance.min.js" type="text/javascript"></script>
        <script src=<?=$this->basePath()?>"/third-party/jQuery-UI-FileInput/js/fileinput.jquery.js" type="text/javascript"></script>
        <!--init for this page-->
        <script type="text/javascript" src=<?=$this->basePath()?>"/js/demo.js"></script>
    <style type="text/css">
      /* Override some defaults */
      html, body {
        background-color: #eee;
      }
      body {
        padding-top: 40px; /* 40px to make the container go all the way to the bottom of the topbar */
      }
      .container > footer p {
        text-align: center; /* center align it with the container */
      }
      .container {
        width: 820px; /* downsize our container to make the content feel a bit tighter and more cohesive. NOTE: this removes two full columns from the grid, meaning you only go to 14 columns and not 16. */
      }
      /* The white background content wrapper */
      .container > .content {
        background-color: #fff;
        padding: 20px;
        margin: 0 -20px; /* negative indent the amount of the padding to maintain the grid system */
        -webkit-border-radius: 0 0 6px 6px;
           -moz-border-radius: 0 0 6px 6px;
                border-radius: 0 0 6px 6px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);
                box-shadow: 0 1px 2px rgba(0,0,0,.15);
      }
      /* Page header tweaks */
      .page-header {
        background-color: #f5f5f5;
        padding: 20px 20px 10px;
        margin: -20px -20px 20px;
      }
      /* Styles you shouldn't keep as they are for displaying this base example only */
      .content .span10,
      .content .span4 {
        min-height: 500px;
      }
      /* Give a quick and non-cross-browser friendly divider */
      .content .span4 {
        margin-left: 0;
        padding-left: 19px;
        border-left: 1px solid #eee;
      }

      .topbar .btn {
        border: 0;
      }
    </style>
  </head>
  <body>
  <!--[if IE]>
  <link rel="stylesheet" type="text/css" href="css/custom-theme/jquery.ui.1.8.16.ie.css"/>
  <![endif]-->
    <div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="#">Project Test</a>
          <ul class="nav">
            <li class="active"><a href="#">Inicio</a></li>
            <li><a href="#">Área</a></li>
            <li><a href="#">Aviso</a></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
          <?php echo $this->content; ?>
      </div>
    </div>
  </body>
</html>
